In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [19]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [20]:
## Preprocess the data
## Drop irrelevant features
data=data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [21]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [22]:
## Onehot encoding-Geography column
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(), columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head(2)

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0

In [23]:
## combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [24]:
## Divide the dataset into independent and dependent features
X=data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary']

## Split the data in training and testing sets
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

#Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [25]:
## save the encoders and scaler
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Regression problem statement

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [27]:
# Build the model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1], )),
    Dense(32, activation='relu'),
    Dense(1) # Output layer for regression
])

## compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

d:\My Desktop\AI\ANN Project\myvenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

#Set up TensorBoard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [30]:
#Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [31]:
# Train the model
history=model.fit(
    X_train, y_train, 
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100385.3359 - mae: 100385.3359 - val_loss: 98544.6328 - val_mae: 98544.6328
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99738.3281 - mae: 99738.3281 - val_loss: 97232.9141 - val_mae: 97232.9141
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 97461.5156 - mae: 97461.5156 - val_loss: 93877.5078 - val_mae: 93877.5078
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 92954.5156 - mae: 92954.5156 - val_loss: 88197.3281 - val_mae: 88197.3281
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 86245.2656 - mae: 86245.2656 - val_loss: 80628.8125 - val_mae: 80628.8125
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 77963.5391 - mae: 77963.5391 - val_loss: 72252.2578 - val_mae: 72252.2578
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 69454.6641 - mae: 69454.6641 - val_loss: 64513.3242 - val_mae: 64513.3242
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 62053.1367 - mae: 62053.1367 - val_loss: 58376.7578 - val_mae: 58376.7578
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 56635.8906 - mae: 56635.8906 - val_loss: 54400.1523 - val_mae: 54400.1523
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53301.4531 - mae: 53301.4531 - val_loss: 52142.3867 - val_mae: 52142.3867
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51585.5117 - mae: 51585.5117 - val_loss: 51252.7305 - val_mae: 51252.7305
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50824.5938 - mae: 50824.5938 - val_loss: 50949.9805 - val_mae: 50949.9805
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50485.6211 - mae: 50485.6211 - val_loss: 50841.2188 - val_mae: 50841.2188
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50318.2539 - mae: 50318.2539 - val_loss: 50785.7969 - val_mae: 50785.7969
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50227.2969 - mae: 50227.2969 - val_loss: 50750.1523 - val_mae: 50750.1523
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50157.1992 - mae: 50157.1992 - val_loss: 50719.0156 - val_mae: 50719.0156
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50101.5391 - mae: 50101.5391 - val_loss: 50689.5391 - val_mae: 50689.5391
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50051.9297 - mae: 50051.9297 - val_loss: 50654.5508 - val_mae: 50654.5508
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50015.0312 - mae: 50015.0312 - val_loss: 50631.3633 - val_mae: 50631.3633
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49976.0039 - mae: 49976.0039 - val_loss: 50609.7070 - val_mae: 50609.7070
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49945.1875 - mae: 49945.1875 - val_loss: 50588.5469 - val_mae: 50588.5469
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49911.6133 - mae: 49911.6133 - val_loss: 50565.7930 - val_mae: 50565.7930
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49887.2422 - mae: 49887.2422 - val_loss: 50549.9297 - val_mae: 50549.9297
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49861.0234 - mae: 49861.0234 - val_loss: 50533.4102 - val_mae: 50533.4102
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49837.8086 - mae: 49837.8086 - val_loss: 50520.1250 - val_mae: 50520.1250
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49817.1602 - mae: 49817.1602 - val_loss: 50501.3359 - val_mae: 50501.3359
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49795.2812 - mae: 49795.2812 - val_loss: 50492.6367 - val_mae: 50492.6367
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49779.1406 - mae: 49779.1406 - val_loss: 50483.1797 - val_mae: 50483.1797
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49756.6016 - mae: 49756.6016 - val_loss: 50465.6797 - val_mae: 50465.6797
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49740.6562 - mae: 49740.6562 - val_loss: 50459.7070 - val_mae: 50459.7070
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49721.7070 - mae: 49721.7070 - val_loss: 50450.6016 - val_mae: 50450.6016
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49707.0547 - mae: 49707.0547 - val_loss: 50443.7656 - val_mae: 50443.7656
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49692.9531 - mae: 49692.9531 - val_loss: 50436.3164 - val_mae: 50436.3164
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49676.7891 - mae: 49676.7891 - val_loss: 50441.3867 - val_mae: 50441.3867
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49661.9766 - mae: 49661.9766 - val_loss: 50429.7656 - val_mae: 50429.7656
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49648.3750 - mae: 49648.3750 - val_loss: 50423.1875 - val_mae: 50423.1875
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49635.1758 - mae: 49635.1758 - val_loss: 50416.5312 - val_mae: 50416.5312
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49624.2891 - mae: 49624.2891 - val_loss: 50413.6758 - val_mae: 50413.6758
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49611.5664 - mae: 49611.5664 - val_loss: 50417.3984 - val_mae: 50417.3984
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49600.8789 - mae: 49600.8789 - val_loss: 50407.5781 - val_mae: 50407.5781
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49590.7148 - mae: 49590.7148 - val_loss: 50403.5234 - val_mae: 50403.5234
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49580.1680 - mae: 49580.1680 - val_loss: 50407.0586 - val_mae: 50407.0586
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49570.2812 - mae: 49570.2812 - val_loss: 50407.2695 - val_mae: 50407.2695
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49561.3242 - mae: 49561.3242 - val_loss: 50401.5898 - val_mae: 50401.5898
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49551.1289 - mae: 49551.1289 - val_loss: 50400.6719 - val_mae: 50400.6719
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49542.6523 - mae: 49542.6523 - val_loss: 50407.2578 - val_mae: 50407.2578
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49534.9727 - mae: 49534.9727 - val_loss: 50402.3359 - val_mae: 50402.3359
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49526.5938 - mae: 49526.5938 - val_loss: 50398.6992 - val_mae: 50398.6992
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49522.2734 - mae: 49522.2734 - val_loss: 50409.9258 - val_mae: 50409.9258
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49512.1055 - mae: 49512.1055 - val_loss: 50405.8789 - val_mae: 50405.8789
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49506.0117 - mae: 49506.0117 - val_loss: 50405.8359 - val_mae: 50405.8359
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49497.1680 - mae: 49497.1680 - val_loss: 50399.3828 - val_mae: 50399.3828
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49492.9531 - mae: 49492.9531 - val_loss: 50418.1641 - val_mae: 50418.1641
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49486.3398 - mae: 49486.3398 - val_loss: 50404.9492 - val_mae: 50404.9492
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49478.0898 - mae: 49478.0898 - val_loss: 50406.5625 - val_mae: 50406.5625
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49474.2344 - mae: 49474.2344 - val_loss: 50414.0117 - val_mae: 50414.0117
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49466.2461 - mae: 49466.2461 - val_loss: 50406.2344 - val_mae: 50406.2344
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49458.9648 - mae: 49458.9648 - val_loss: 50400.7969 - val_mae: 50400.7969

In [32]:
%load_ext tensorboard

In [37]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 9372), started 0:00:03 ago. (Use '!kill 9372' to kill it.)

In [38]:
# Evaluatemodel on the test data
test_loss, test_mae=model.evaluate(X_test, y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50398.6992 - mae: 50398.6992
Test MAE : 50398.69921875

In [39]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.